services:

  db:
    container_name: postgresql
    image: postgres:12.0-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  redis:
    image: redis:6-alpine
    restart: always
    ports:
      - 6379:6379

  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      # NOTE: development-only options
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      # NOTE: development-only option
    ports:
      - 9092:9092

  profile-service:
    build: ./profile_service
    volumes: 
      - ./profile_service:/app
    ports:
      - 8080:8000
    depends_on:
      - db

  swipe-service:
    build: ./swipe_service
    ports:
      - 8081:8000
    depends_on:
      - db
