services:

  db:
    container_name: postgresql
    image: postgres:12.0-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  redis:
    container_name: redis
    image: redis:6-alpine
    restart: always
    ports:
      - 6379:6379

  kafka:
    container_name: kafka
    image: 'apache/kafka:latest'
    restart: always
    ports:
      - 9092:9092

  profile-service:
    container_name: profile-service 
    build: ./profile_service
    volumes: 
      - ./profile_service:/app
    ports:
      - 8080:8000
    depends_on:
      - db

  swipe-service:
    container_name: swipe-service 
    build: ./swipe_service
    ports:
      - 8081:8000
    depends_on:
      - db
      - kafka

  deck-service:
    container_name: deck-service 
    build: ./deck_service
    volumes: 
      - ./deck_service:/app
    depends_on:
      - db
      - redis

  notification-service:
    container_name: notification-service 
    build: ./notification_service
    volumes: 
      - ./notification_service:/app
    depends_on:
      - db
      - redis
      - kafka

